apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: hello-world-app
spec: 
  containers:
    - name: hello-world-container
      image: karthequian/helloworld
      ports:
        - containerPort: 80